// leave off @2x/@3x
const images = {
	iconListActive: require('../Images/Icons/list_active.png'),
	iconListInactive: require('../Images/Icons/list_inactive.png'),
	iconProfileActive: require('../Images/Icons/profile_active.png'),
	iconProfileInactive: require('../Images/Icons/profile_inactive.png'),
	iconRadarActive: require('../Images/Icons/radar_active.png'),
	iconRadarInactive: require('../Images/Icons/radar_inactive.png'),
	iconArrowLeft: require('../Images/Icons/arrow_left.png'),
	iconArrowRight: require('../Images/Icons/arrow_right.png'),
	launch: require('../Images/launch-icon.png'),
	ignite: require('../Images/ignite_logo.png'),
	igniteClear: require('../Images/ignite-logo-transparent.png'),
	iconLock: require('../Images/Icons/lock-icon.png'),
	iconLeading: require('../Images/Icons/leading-icon.png'),
	eye: require('../Images/Icons/eye.png'),
	eyeOff: require('../Images/Icons/eye-off.png'),
	clear: require('../Images/Icons/clear.png'),
	courses: require('../Images/courses.png'),
	iconLesson1: require('../Images/lesson-1.png'),
	iconLesson2: require('../Images/lesson-2.png'),
	iconCourse: require('../Images/Icons/course.png'),
	iconClock: require('../Images/Icons/clock.png'),
	iconArrowLeftBlack: require('../Images/Icons/icon-arrow-left-black.png'),
	iconArrowLeftWhite: require('../Images/Icons/icon-arrow-left-white.png'),
	iconBigClock: require('../Images/Icons/icon-big-clock.png'),
	iconBookActive: require('../Images/Icons/icon-book-active.png'),
	iconBookInactive: require('../Images/Icons/icon-book-inactive.png'),
	iconHomeActive: require('../Images/Icons/icon-home-active.png'),
	iconHomeInactive: require('../Images/Icons/icon-home-inactive.png'),
	iconUserActive: require('../Images/Icons/icon-user-active.png'),
	iconUserInactive: require('../Images/Icons/icon-user-inactive.png'),
	iconCategory1: require('../Images/Icons/icon-category-1.png'),
	iconCategory2: require('../Images/Icons/icon-category-2.png'),
	jambo: require('../Images/logo-jambo.png'),
	iconFb: require('../Images/Icons/icon-fb.png'),
	newJambo: require('../Images/new-logo-jambo.png')
};

export default images;
